# Generated by Django 4.2.29 on 2026-03-26 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_opportunity_stage_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '商机跟进', 'verbose_name_plural': '商机跟进'},
        ),
        migrations.AlterModelOptions(
            name='approvalflow',
            options={'verbose_name': '审批流程', 'verbose_name_plural': '审批流程'},
        ),
        migrations.AlterModelOptions(
            name='approvalinstance',
            options={'verbose_name': '审批实例', 'verbose_name_plural': '审批实例'},
        ),
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'ordering': ['order'], 'verbose_name': '审批步骤', 'verbose_name_plural': '审批步骤'},
        ),
        migrations.AlterModelOptions(
            name='approvaltask',
            options={'verbose_name': '审批任务', 'verbose_name_plural': '审批任务'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '联系人', 'verbose_name_plural': '联系人'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '开票申请', 'verbose_name_plural': '开票申请'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': '线索', 'verbose_name_plural': '线索'},
        ),
        migrations.AlterModelOptions(
            name='lookupcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '字典类别', 'verbose_name_plural': '字典类别'},
        ),
        migrations.AlterModelOptions(
            name='lookupoption',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '字典选项', 'verbose_name_plural': '字典选项'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': '商机', 'verbose_name_plural': '商机'},
        ),
        migrations.AlterModelOptions(
            name='opportunityattachment',
            options={'verbose_name': '商机附件', 'verbose_name_plural': '商机附件'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '回款', 'verbose_name_plural': '回款'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': '报价', 'verbose_name_plural': '报价'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '区域', 'verbose_name_plural': '区域'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': '角色权限', 'verbose_name_plural': '角色权限'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_customer_levels', to='core.lookupoption', verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='account',
            name='enterprise_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_enterprise_natures', to='core.lookupoption', verbose_name='企业性质'),
        ),
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='客户全称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='account',
            name='scale',
            field=models.CharField(blank=True, max_length=100, verbose_name='企业规模'),
        ),
        migrations.AlterField(
            model_name='account',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='客户简称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('archived', '归档')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, verbose_name='官网'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', '电话'), ('meeting', '会议'), ('email', '邮件'), ('visit', '拜访')], default='call', max_length=20, verbose_name='跟进方式'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='跟进时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.lead', verbose_name='线索'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='跟进主题'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='name',
            field=models.CharField(max_length=200, verbose_name='流程名称'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_flows', to='core.region', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='target_type',
            field=models.CharField(choices=[('quote', '报价'), ('contract', '合同'), ('invoice', '开票')], max_length=20, verbose_name='审批对象'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='对象类型'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='current_step',
            field=models.PositiveIntegerField(default=1, verbose_name='当前步骤'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_instances', to='core.region', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_approvals', to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='target_type',
            field=models.CharField(choices=[('quote', '报价'), ('contract', '合同'), ('invoice', '开票')], max_length=20, verbose_name='审批对象'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.role', verbose_name='审批角色'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.approvalflow', verbose_name='流程'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='name',
            field=models.CharField(max_length=200, verbose_name='步骤名称'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='order',
            field=models.PositiveIntegerField(verbose_name='步骤顺序'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='comment',
            field=models.TextField(blank=True, verbose_name='审批意见'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.approvalinstance', verbose_name='审批实例'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已同意'), ('rejected', '已拒绝'), ('blocked', '未轮到')], default='blocked', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.approvalstep', verbose_name='审批步骤'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='core.account', verbose_name='所属客户'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_key_person',
            field=models.BooleanField(default=False, verbose_name='是否关键人'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preference',
            field=models.CharField(blank=True, max_length=200, verbose_name='偏好/标签'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='remark',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='final_settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最终结算金额'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_at',
            field=models.DateField(blank=True, null=True, verbose_name='签署日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('signed', '已签署'), ('active', '执行中'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='开票金额'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.contract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='开票编号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('special', '专票'), ('normal', '普票')], default='normal', max_length=20, verbose_name='开票类型'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='开票日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('issued', '已开票'), ('paid', '已回款'), ('void', '作废')], default='draft', max_length=20, verbose_name='开票状态'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, verbose_name='线索描述'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预估金额'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200, verbose_name='线索名称'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='线索来源'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='new', max_length=50, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='类别编码'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='lookupcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.lookupcategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='code',
            field=models.CharField(max_length=50, verbose_name='选项编码'),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='选项名称'),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际成交金额'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='actual_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='商机成交时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.contact', verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_customer_levels', to='core.lookupoption', verbose_name='客户级别'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='enterprise_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_enterprise_natures', to='core.lookupoption', verbose_name='企业性质'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预计成交金额'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计成交时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='has_intermediary',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否有居间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='kpi_25_met',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否满足经营指标25%'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='latest_followup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最新跟进记录时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='latest_followup_note',
            field=models.TextField(blank=True, null=True, verbose_name='最新跟进记录'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='core.lead', verbose_name='线索'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_lead_sources', to='core.lookupoption', verbose_name='线索来源'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_categories', to='core.lookupoption', verbose_name='商机分类'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_name',
            field=models.CharField(max_length=200, verbose_name='商机名称'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_product_needs', to='core.lookupoption', verbose_name='需求产品'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='阶段进入时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='suspended_at',
            field=models.DateField(blank=True, null=True, verbose_name='商机挂起时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_user_groups', to='core.lookupoption', verbose_name='用户群体'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='win_probability',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='成交概率%'),
        ),
        migrations.AlterField(
            model_name='opportunityattachment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='opportunityattachment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='回款金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.contract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.invoice', verbose_name='开票'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='回款日期'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='period_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='回款期次'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receivable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='应收金额'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='回款编号/备注'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('planned', '计划中'), ('partial', '部分回款'), ('paid', '已回款')], default='planned', max_length=20, verbose_name='回款状态'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='报价金额'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='报价日期'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='报价状态'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='区域编码'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='region',
            name='dingtalk_dept_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='钉钉部门ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.region', verbose_name='上级区域'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='角色编码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('self', '仅本人'), ('region', '本区域'), ('region_and_children', '本区域及下级'), ('all', '全部')], default='region_and_children', max_length=32, verbose_name='数据范围'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_approve',
            field=models.BooleanField(default=False, verbose_name='可审批'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_create',
            field=models.BooleanField(default=True, verbose_name='可创建'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_delete',
            field=models.BooleanField(default=False, verbose_name='可删除'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='can_update',
            field=models.BooleanField(default=True, verbose_name='可更新'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('lead', '线索'), ('opportunity', '商机'), ('account', '客户'), ('contact', '联系人'), ('quote', '报价'), ('contract', '合同'), ('invoice', '开票'), ('payment', '回款'), ('activity', '商机跟进'), ('task', '任务')], max_length=32, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='task',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.contract', verbose_name='合同'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='截止时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.lead', verbose_name='线索'),
        ),
        migrations.AlterField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.opportunity', verbose_name='商机'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '进行中'), ('done', '已完成'), ('canceled', '已取消')], default='open', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='任务标题'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dingtalk_union_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='钉钉UnionID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dingtalk_user_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='钉钉用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.region', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role', verbose_name='角色'),
        ),
    ]
