# Generated by Django 4.2.29 on 2026-03-30 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contract_receivable_urgent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractattachment',
            options={'verbose_name': '合同附件', 'verbose_name_plural': '合同附件'},
        ),
        migrations.AlterField(
            model_name='contractattachment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='contractattachment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='core.region', verbose_name='所属区域'),
        ),
    ]
