# Generated by Django 4.2.29 on 2026-03-31 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_contractattachment_options_and_more'),
        ('core', '0016_remove_approval_models'),
    ]

    operations = [
    ]
