# Generated by Django 4.2.29 on 2026-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_account_created_by_account_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_framework',
            field=models.BooleanField(default=False, verbose_name='是否为框架合同'),
        ),
    ]
