# Generated by Django 4.2.29 on 2026-04-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_activity_created_by_activity_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='framework_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_contracts', to='core.contract', verbose_name='所属框架合同'),
        ),
    ]
