# Generated by Django 4.2.29 on 2026-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_contract_framework_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('lead', '线索阶段'), ('opportunity', '商机阶段'), ('demand', '需求引导'), ('solution', '方案阶段'), ('bid', '投标阶段'), ('business', '商务谈判'), ('contract', '合同审批'), ('won', '成交关闭'), ('framework', '框架合作'), ('lost', '商机关闭')], default='lead', max_length=32, verbose_name='商机阶段'),
        ),
    ]
