# Generated by Django 4.2.29 on 2026-04-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contract_remark_alter_opportunity_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='回款说明'),
        ),
    ]
