# Generated by Django 4.2.29 on 2026-04-10 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_common_doc_role_permissions(apps, schema_editor):
    Role = apps.get_model('core', 'Role')
    RolePermission = apps.get_model('core', 'RolePermission')
    for role in Role.objects.all():
        RolePermission.objects.get_or_create(
            role=role,
            module='common_doc',
            defaults={
                'can_create': True,
                'can_update': True,
                'can_delete': False,
                'can_approve': False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contact_created_by_contact_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonDocDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='目录名称')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_doc_directory_created_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_doc_directory_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '常用文档目录',
                'verbose_name_plural': '常用文档目录',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('lead', '线索'), ('opportunity', '商机'), ('account', '客户'), ('contact', '联系人'), ('quote', '报价'), ('contract', '合同'), ('invoice', '开票'), ('payment', '回款'), ('activity', '商机跟进'), ('task', '任务'), ('common_doc', '常用文档')], max_length=32, verbose_name='模块'),
        ),
        migrations.RunPython(create_common_doc_role_permissions, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CommonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='common_documents/%Y/%m/', verbose_name='文档文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='文档备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_document_created_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.commondocdirectory', verbose_name='目录')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_document_updated_items', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '常用文档',
                'verbose_name_plural': '常用文档',
                'ordering': ['-created_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommonDocDirectoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='可查看')),
                ('can_download', models.BooleanField(default=False, verbose_name='可下载')),
                ('can_upload', models.BooleanField(default=False, verbose_name='可上传')),
                ('can_edit', models.BooleanField(default=False, verbose_name='可编辑')),
                ('can_delete', models.BooleanField(default=False, verbose_name='可删除')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.commondocdirectory', verbose_name='目录')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_doc_permissions', to='core.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '常用文档目录权限',
                'verbose_name_plural': '常用文档目录权限',
                'unique_together': {('directory', 'role')},
            },
        ),
    ]
