# Generated by Django 4.2.29 on 2026-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_commondocdirectory_alter_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalModuleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True, verbose_name='单例键')),
                ('contract_approval_enabled', models.BooleanField(default=True, verbose_name='启用合同审批')),
                ('invoice_approval_enabled', models.BooleanField(default=True, verbose_name='启用开票审批')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批模块开关',
                'verbose_name_plural': '审批模块开关',
            },
        ),
    ]
