# Generated by Django 4.2.29 on 2026-04-14 08:12

from django.db import migrations, models


def backfill_user_roles(apps, schema_editor):
    User = apps.get_model('core', 'User')
    through_model = User.roles.through

    records = []
    for user in User.objects.exclude(role_id__isnull=True).only('id', 'role_id').iterator():
        records.append(through_model(user_id=user.id, role_id=user.role_id))

    if records:
        through_model.objects.bulk_create(records, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_approvalmodulesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='multi_role_users', to='core.role', verbose_name='角色列表'),
        ),
        migrations.RunPython(backfill_user_roles, migrations.RunPython.noop),
    ]
