# Generated by Django 4.2.29 on 2026-04-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='approval_status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回'), ('revising', '修订中')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
    ]
