# Generated by Django 4.2.29 on 2026-04-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_contract_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNoSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(unique=True, verbose_name='日期')),
                ('last_serial', models.PositiveIntegerField(default=0, verbose_name='最后流水号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合同编号日流水',
                'verbose_name_plural': '合同编号日流水',
            },
        ),
    ]
