# Generated by Django 4.2.29 on 2026-04-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contractnosequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='银行账号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='开户银行'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxpayer_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='纳税人识别号'),
        ),
    ]
