# Generated by Django 4.2.29 on 2026-04-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='todo_channel',
            field=models.CharField(choices=[('own_oa', '钉钉自建审批'), ('todo_api', '钉钉Todo开放接口'), ('disabled', '未启用'), ('unknown', '未知通道')], default='unknown', max_length=20, verbose_name='待办通道'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_last_error',
            field=models.TextField(blank=True, verbose_name='待办错误信息'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='待办下次重试时间'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='待办重试次数'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_source_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='待办来源ID'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_status',
            field=models.CharField(choices=[('init', '未处理'), ('queued', '排队中'), ('created', '已创建'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='init', max_length=20, verbose_name='待办状态'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='todo_task_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='钉钉待办ID'),
        ),
        migrations.AlterField(
            model_name='approvalinstance',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已审批'), ('rejected', '已驳回'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('approved', '已同意'), ('rejected', '已拒绝'), ('blocked', '未轮到'), ('canceled', '已关闭')], default='blocked', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ApprovalActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '发起审批'), ('task_activated', '任务激活'), ('approved', '审批通过'), ('rejected', '审批驳回'), ('withdrawn', '审批撤回'), ('completed', '流程完成'), ('todo_create', '创建待办'), ('todo_complete', '完成待办'), ('todo_failed', '待办失败')], max_length=32, verbose_name='动作')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='approval.approvalinstance', verbose_name='审批实例')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='approval.approvaltask', verbose_name='审批任务')),
            ],
            options={
                'verbose_name': '审批动作日志',
                'verbose_name_plural': '审批动作日志',
                'db_table': 'core_approvalactionlog',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalTodoOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建待办'), ('complete', '完成待办')], max_length=20, verbose_name='动作')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('succeeded', '成功'), ('failed', '失败待重试'), ('dead', '死信')], default='pending', max_length=20, verbose_name='状态')),
                ('source_id', models.CharField(blank=True, max_length=120, verbose_name='来源ID')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='负载数据')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('next_retry_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次重试时间')),
                ('last_error', models.TextField(blank=True, verbose_name='最后错误')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_outbox_items', to='approval.approvaltask', verbose_name='审批任务')),
            ],
            options={
                'verbose_name': '审批待办队列',
                'verbose_name_plural': '审批待办队列',
                'db_table': 'core_approvaltodooutbox',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='core_approv_status_40b313_idx'), models.Index(fields=['action', 'source_id'], name='core_approv_action_83ca40_idx')],
            },
        ),
    ]
