# Generated by Django 4.2.29 on 2026-04-14 15:10

from django.db import migrations, models
from django.db.models import Q


def forwards_data(apps, schema_editor):
    ApprovalFlow = apps.get_model('approval', 'ApprovalFlow')
    ApprovalStep = apps.get_model('approval', 'ApprovalStep')

    for flow in ApprovalFlow.objects.all().order_by('id'):
        if flow.region_id:
            flow.scope_mode = 'selected_regions'
        else:
            flow.scope_mode = 'all_regions'
        flow.save(update_fields=['scope_mode'])
        if flow.region_id:
            flow.regions.add(flow.region_id)

    for flow in ApprovalFlow.objects.all().order_by('id'):
        steps = list(ApprovalStep.objects.filter(flow_id=flow.id).order_by('order', 'id'))
        for index, step in enumerate(steps, start=1):
            update_fields = []
            if step.order != index:
                step.order = index
                update_fields.append('order')
            if step.approver_user_id:
                if step.approver_role_id:
                    step.approver_role_id = None
                    update_fields.append('approver_role')
                if step.assignee_type != 'user':
                    step.assignee_type = 'user'
                    update_fields.append('assignee_type')
                if step.assignee_scope != 'region':
                    step.assignee_scope = 'region'
                    update_fields.append('assignee_scope')
            elif step.approver_role_id:
                if step.assignee_type != 'role':
                    step.assignee_type = 'role'
                    update_fields.append('assignee_type')
                if step.assignee_scope not in ('region', 'global'):
                    step.assignee_scope = 'region'
                    update_fields.append('assignee_scope')
            else:
                if step.assignee_type != 'role':
                    step.assignee_type = 'role'
                    update_fields.append('assignee_type')
                if step.assignee_scope != 'region':
                    step.assignee_scope = 'region'
                    update_fields.append('assignee_scope')
            if update_fields:
                step.save(update_fields=update_fields)


def reverse_data(apps, schema_editor):
    ApprovalFlow = apps.get_model('approval', 'ApprovalFlow')
    ApprovalStep = apps.get_model('approval', 'ApprovalStep')

    for flow in ApprovalFlow.objects.all().order_by('id'):
        first_region_id = flow.regions.order_by('id').values_list('id', flat=True).first()
        flow.region_id = first_region_id
        flow.save(update_fields=['region'])

    for step in ApprovalStep.objects.all().order_by('id'):
        if step.approver_user_id:
            step.assignee_type = 'user'
        else:
            step.assignee_type = 'role'
        step.assignee_scope = 'region'
        step.save(update_fields=['assignee_type', 'assignee_scope'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_approvalmodulesetting'),
        ('approval', '0002_approvaltask_todo_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='scope_mode',
            field=models.CharField(
                choices=[('all_regions', '全部区域'), ('selected_regions', '指定区域')],
                default='all_regions',
                max_length=20,
                verbose_name='适用范围',
            ),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='regions',
            field=models.ManyToManyField(
                blank=True,
                related_name='scoped_approval_flows',
                to='core.region',
                verbose_name='适用区域',
            ),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assignee_scope',
            field=models.CharField(
                choices=[('region', '按发起区域匹配'), ('global', '全局匹配')],
                default='region',
                max_length=20,
                verbose_name='审批人作用域',
            ),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='assignee_type',
            field=models.CharField(
                choices=[('user', '指定用户'), ('role', '指定角色')],
                default='role',
                max_length=20,
                verbose_name='审批人类型',
            ),
        ),
        migrations.RunPython(forwards_data, reverse_data),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='uniq_approval_step_flow_order'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.CheckConstraint(
                check=~(Q(approver_user__isnull=False) & Q(approver_role__isnull=False)),
                name='chk_approval_step_no_both_user_and_role',
            ),
        ),
    ]
