# Generated by Django 4.2.29 on 2026-04-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_flow_scope_and_step_assignee_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_sign_children', to='approval.approvaltask', verbose_name='来源任务'),
        ),
    ]
