# Generated by Django 4.2.29 on 2026-04-15 04:46

from django.db import migrations, models


def sync_flow_status_from_is_active(apps, schema_editor):
    ApprovalFlow = apps.get_model('approval', 'ApprovalFlow')
    ApprovalFlow.objects.filter(is_active=False).update(status='draft')
    ApprovalFlow.objects.filter(is_active=True).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_approvaltask_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalflow',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效开始时间'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生效结束时间'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='published', max_length=20, verbose_name='流程状态'),
        ),
        migrations.RunPython(sync_flow_status_from_is_active, migrations.RunPython.noop),
    ]
